### ISSUE TITLE
Tests for the various interfaces

### ISSUE THREAD

**Issue by Mikerah** [libp2p/go-libp2p-core#101]
I'm in the midst of writing my own libp2p transport. However, it would be very helpful to have interface tests like [this js transport interface](https://github.com/libp2p/interface-transport) so that at the very least we, as transport writers, can ensure that we have the basic functionality to ensure that our transports work with libp2p.

**Comment by Stebalien** [comment]
Take a look at https://github.com/libp2p/go-libp2p-testing/tree/master/suites/transport.

**Comment by Stebalien** [comment]
(you can see how they're used by the TCP transport).

**Comment by Mikerah** [comment]
Thanks a lot. I didn't see that.

**Comment by Stebalien** [comment]
Would you consider filing a PR against this repo's README linking to that project? It's not very discoverable.
