### ISSUE TITLE
Go docs not displaying on Pkg.go.dev because of "license restrictions"

### ISSUE THREAD

**Issue by zot** [libp2p/go-libp2p-core#114]
You can see [here](https://pkg.go.dev/github.com/libp2p/go-libp2p-core?tab=doc) that the docs are not being displayed on the new docs site. It looks like having two licenses is not well supported. I'm sending an email to go-discovery-feedback@google.com about it with a link to this issue and hopefully they'll resolve it. Their site says [here](https://pkg.go.dev/license-policy) that they're using licensecheck but I think it's the code that's using lisensecheck that's at fault, not licensecheck itself.

**Comment by jba** [comment]
pkg.go.dev should now show this project correctly.

**Comment by Stebalien** [comment]
Awesome! This also fixed go-ipfs.
