### ISSUE TITLE
Error in using libp2pquic.NewTransport with libp2p.Transport

### ISSUE THREAD

**Issue by Gauthamastro** [libp2p/go-libp2p-core#156]
I am getting 

> argument 2 has an unexpected type ConnectionGater

when am trying to create a libp2p host as follows
`
libp2p.Transport(libp2pquic.NewTransport), 
`
I am using the github.com/libp2p/go-libp2p-quic-transport v0.4.0 and github.com/libp2p/go-libp2p-core v0.5.6. 

Can you please help me resolve this issue?

EDIT: I am able to resolve this error by downgrading go-libp2p-quic-transport v0.3.7, I think go-libp2p-core v0.5.6. doesn't yet support the Conngating that is included in go-libp2p-quic-transport v0.4.0

**Comment by raulk** [comment]
Can you please upgrade go-libp2p to the latest release?

**Comment by Gauthamastro** [comment]
> Can you please upgrade go-libp2p to the latest release?

Yes, It is now working. Thanks!
