### ISSUE TITLE
Record envelope protobuf does not match spec

### ISSUE THREAD

**Issue by jacobheun** [libp2p/go-libp2p-core#160]
Signature index here is set to 5,  https://github.com/libp2p/go-libp2p-core/blob/v0.6.0/record/pb/envelope.proto#L29.

The spec is 4, which is should be. https://github.com/libp2p/specs/pull/217/files#diff-1d3e44bb1e34e0581019f35b96151a0dR70

**Comment by aschmahmann** [comment]
@jacobheun is this issue closed since the spec was changed to match?

**Comment by jacobheun** [comment]
Yep, closing.
