### ISSUE TITLE
Add a `ClearDeadline` API

### ISSUE THREAD

**Issue by schomatis** [libp2p/go-libp2p-core#162]
https://github.com/libp2p/go-libp2p-core/blob/98f971425855d14dd69d563d11db1e5fa37cc9f3/mux/mux.go#L30-L32

(Same for read/write variants.)

**Comment by Stebalien** [comment]
Call `SetDeadline(time.Time{})` to clear the timeout. See the interface documentation in https://golang.org/pkg/net/#Conn.

**Comment by schomatis** [comment]
Yeah, I'm aware of that, I had hope _we_ could provide a more user-friendly API on this one.

**Comment by Stebalien** [comment]
I mean, we _could_, but then we'd have to implement it everywhere and we'd be deviating from the standard library at the same time. That's a lot of work/documentation for a papercut.

**Comment by schomatis** [comment]
Fair enough, if this has many repercussions throughout other repos is not worth it.
