### ISSUE TITLE
v0.7.0 breaks backward compatibility for multiple packages

### ISSUE THREAD

**Issue by lthibault** [libp2p/go-libp2p-core#168]
Hello,

I've just upgraded to `github.com/libp2p/go-libp2p-core@v0.7.0`, which [removes `helpers.FullClose`](https://github.com/libp2p/go-libp2p-core/commit/d6afc690e1c63a66c91193d5acc60b8731311bbd#diff-374968fca2d4ee2436e6c25d6932a7a0L18-L31).  As of this upgrade, the following packages are broken:

- `github.com/libp2p/go-libp2p@v0.11.0`
- `github.com/libp2p/go-libp2p-kad-dht@v0.10.0`
- `github.com/libp2p/go-libp2p-pubsub@v0.3.5`

Here's the error message that appears:

```
# github.com/libp2p/go-libp2p/p2p/protocol/identify
../../../../pkg/mod/github.com/libp2p/go-libp2p@v0.11.0/p2p/protocol/identify/id.go:380:3: undefined: helpers.FullClose
../../../../pkg/mod/github.com/libp2p/go-libp2p@v0.11.0/p2p/protocol/identify/id.go:424:20: undefined: helpers.FullClose
../../../../pkg/mod/github.com/libp2p/go-libp2p@v0.11.0/p2p/protocol/identify/id_delta.go:29:8: undefined: helpers.FullClose
../../../../pkg/mod/github.com/libp2p/go-libp2p@v0.11.0/p2p/protocol/identify/peer_loop.go:132:8: undefined: helpers.FullClose
../../../../pkg/mod/github.com/libp2p/go-libp2p@v0.11.0/p2p/protocol/identify/peer_loop.go:153:8: undefined: helpers.FullClose
# github.com/libp2p/go-libp2p-pubsub
../../../../pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.3.5/comm.go:128:8: undefined: helpers.FullClose
../../../../pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.3.5/tracer.go:263:5: undefined: helpers.FullClose
# github.com/libp2p/go-libp2p-kad-dht
../../../../pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.10.0/dht_net.go:396:7: undefined: helpers.FullClose
../../../../pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.10.0/dht_net.go:446:7: undefined: helpers.FullClose
```

**Comment by aschmahmann** [comment]
@lthibault I recommend taking a look at the release notes https://github.com/libp2p/go-libp2p-core/releases/tag/v0.7.0. This release contains breaking changes which means that dependencies will have to get updated (e.g. https://github.com/libp2p/go-libp2p/pull/1001).

If you're interested in why this change was made take a look at the corresponding PR (https://github.com/libp2p/go-libp2p-core/pull/166)

**Comment by lthibault** [comment]
@aschmahmann  Thanks for the quick reply!

If I understand correctly, the solution here is to wait for these packages to be updated?  (Totally fine.  Just asking 🙂)

**Comment by Stebalien** [comment]
Yes.
