### ISSUE TITLE
add WithStat option for host.NewStream

### ISSUE THREAD

**Issue by printfcoder** [libp2p/go-libp2p-core#169]
i read the code and find that there is no method to set Stat for Stream. right?

**Comment by printfcoder** [comment]
Emm. I mean how to set the Stat option of Stream? [here](https://github.com/libp2p/go-libp2p-core/blob/master/network/stream.go#L24)

**Comment by Stebalien** [comment]
You don't. It returns read-only info about the stream similar to calling `stat` on a file.
