### ISSUE TITLE
flaky TestResetBandwidthCounter test

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p-core#195]
This is what prevents us from moving to the Unified CI setup (#189). This test is quite annoying, as it relies on `time.Sleep` invocations, and therefore takes 2s.

```
go test -run TestResetBandwidthCounter -count 100 -v ./metrics
```

Unfortunately, our flow metrics depend on `time.Now()`, there's no way to inject a clock interface, which we could mock in tests.

**Comment by Stebalien** [comment]
I'm happy to disable these tests for now. But yeah, the ability to mock time here would be even better.
