### ISSUE TITLE
What happened to the method in **helps**?

### ISSUE THREAD

**Issue by 99Kies** [libp2p/go-libp2p-core#197]
![image](https://user-images.githubusercontent.com/45918704/120098085-852bd780-c166-11eb-92b0-c9f528f21fc5.png)
![image](https://user-images.githubusercontent.com/45918704/120098103-94128a00-c166-11eb-9846-f84eee74a78a.png)

**Comment by aschmahmann** [comment]
The stream interfaces were upgraded to make the helpers no longer necessary. See the release notes for more details (and generally look at release notes when there are minor version bumps.

https://github.com/libp2p/go-libp2p-core/releases/tag/v0.7.0

https://github.com/libp2p/go-libp2p/releases/tag/v0.12.0

Note: GitHub issues are best used to discuss bugs and feature requests whereas support is better discussed on discuss.libp2p.io as forum posts are easier to discover than closed GitHub issues.
