### ISSUE TITLE
Adding metods to an interface is a breaking change.

### ISSUE THREAD

**Issue by Kubuxu** [libp2p/go-libp2p-core#23]
By adding `EventBus()` method to Host interface and releasing 0.0.4 a lot of projects will stop to build after dependency update.

I would suggest considering an act of adding a method to an interface a breaking change and:
1. be careful about it (first update and release the implementation)
2. increase version number accordingly. As we are still in v0, this would mean incrementing minor version number.

**Comment by raulk** [comment]
Yeah, 100%. This is my bad. I should’ve:

1. Released this with a minor version bump at the very least.
2. Merged the go-libp2p PR quicker; we made significant changes to the eventbus last Friday, and the PR stayed dangling over the weekend.

Anyway, things should now be fixed. I released go-libp2p with both a patch bump for consistency, and a minor bump for correctness.

**Comment by raulk** [comment]
CC @lanzafame @prestonvanloop as affected parties.
