### ISSUE TITLE
looks unsafe

### ISSUE THREAD

**Issue by kusattapangod** [libp2p/go-libp2p-core#236]
The code base looks very large. How do you achieve zero vulnerability state(its important for P2Pnetwork).

**Comment by vyzo** [comment]
there is no silvet bullet for achieving zero vulnerabilities in any software project.
Anyone claiming otherwise is selling you snake oil.

**Comment by kusattapangod** [comment]
It sounds like a excuse. For example, bitcoin network is working well with zero vulnerabilities. 
Vulnerabilities in P2P network can have fatal consequences.

You need to be more careful with security vulnerabilities .
