### ISSUE TITLE
Requesting release 0.16 with "update btcec dependency" change

### ISSUE THREAD

**Issue by brianathere** [libp2p/go-libp2p-core#248]

**Comment by marten-seemann** [comment]
Is there any reason to release this right now, and not according to our regular release schedule?

**Comment by brianathere** [comment]
> Is there any reason to release this right now, and not according to our regular release schedule?

We're working on changes to the matrix dendrite server, which depends on this change landing to get us past a diamond dependency issue when we bring in go-ethereum into the dendrite code base. Not urgent, but would like to get closure. When is the next scheduled release?

**Comment by marten-seemann** [comment]
It's scheduled to happen within the next 2 weeks.
