### ISSUE TITLE
btcec update leads to `go mod tidy` failure

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p-core#252]
We just released v0.16.0, which include the btcec update (https://github.com/libp2p/go-libp2p-core/pull/245).

`go mod tidy` now produces the following error (see https://github.com/libp2p/go-libp2p/pull/1521):

```
❯ go mod tidy
github.com/libp2p/go-libp2p imports
        github.com/libp2p/go-libp2p-core/crypto imports
        github.com/btcsuite/btcd/btcec/v2/ecdsa tested by
        github.com/btcsuite/btcd/btcec/v2/ecdsa.test imports
        github.com/btcsuite/btcd/chaincfg/chainhash loaded from github.com/btcsuite/btcd@v0.22.0-beta,
        but go 1.16 would fail to locate it:
        ambiguous import: found package github.com/btcsuite/btcd/chaincfg/chainhash in multiple modules:
        github.com/btcsuite/btcd v0.22.0-beta (/Users/marten/src/go/pkg/mod/github.com/btcsuite/btcd@v0.22.0-beta/chaincfg/chainhash)
        github.com/btcsuite/btcd/chaincfg/chainhash v1.0.0 (/Users/marten/src/go/pkg/mod/github.com/btcsuite/btcd/chaincfg/chainhash@v1.0.0)

To proceed despite packages unresolved in go 1.16:
        go mod tidy -e
If reproducibility with go 1.16 is not needed:
        go mod tidy -compat=1.17
For other options, see:
        https://golang.org/doc/modules/pruning
```

Updating btced to v2.2.0 (from v2.1.3) doesn't solve the problem. I also haven't succeeded in manually adding `github.com/btcsuite/btcd/chaincfg/chainhash` to go-libp2p's `go.mod` file.
People had a similar issue in https://github.com/btcsuite/btcd/issues/1839, but I couldn't make it work in go-libp2p either.

This is now blocking the go-libp2p v0.20.0 release. I'm planning to revert #245, unless we can get this solved within the next 24 hours or so.

cc @brianathere

**Comment by brianathere** [comment]
Looking at this now.

**Comment by vyzo** [comment]
Can we fix our CI globally to do 1.17 compat tidy?
We've had this problem elsewhere too.

**Comment by marten-seemann** [comment]
> Can we fix our CI globally to do 1.17 compat tidy?

We could, but the problem is that _every_ user of go-libp2p would not be able to run a normal `go mod tidy` any more.

I don't really understand why the Go tool would care about 1.16 when the `go.mod` file clearly states `go 1.17` (as all our `go.mod` files do), but apparently that's what the Go team decided.

**Comment by galargh** [comment]
I found another change that makes the errors go away - see https://github.com/libp2p/go-libp2p/pull/1524 - but I'm yet to understand exactly what's going on.

**Comment by marten-seemann** [comment]
Adding the following file to go-libp2p works:

```go
//go:build !go1.17
// +build !go1.17

package libp2p

import (
	_ "github.com/btcsuite/btcd/chaincfg"
)
```

and then making sure that `go.mod` has `require github.com/btcsuite/btcd v0.22.1`.

**Comment by marten-seemann** [comment]
This could also be applied in this repo: https://github.com/libp2p/go-libp2p-core/pull/254

Not sure where the right place for this to live would be. Thoughts?

**Comment by galargh** [comment]
> This could also be applied in this repo: #254
> 
> Not sure where the right place for this to live would be. Thoughts?

Nice! I tested it locally and it seems to do the trick :)

**Comment by galargh** [comment]
On a second thought, maybe https://github.com/libp2p/go-libp2p-core/issues/252#issuecomment-1136262604 fits better here because we'd be able to remove it once we stop transitively depending on lower versions?

Either way, I think yours is better than my replace all.
