### ISSUE TITLE
extend `peer.Set` with the Remove method

### ISSUE THREAD

**Issue by vgonkivs** [libp2p/go-libp2p-core#260]
Currently `peer.Set` allows only to add peers but it would be nice to have a remove functionality.

**Comment by marten-seemann** [comment]
Actually, I'd be in favor of removing the `peer.Set` altogether. The only consumer I can find is kad-dht ([here](https://github.com/libp2p/go-libp2p-kad-dht/blob/4371650e37662cdfd9f5777240c67b861af26092/routing.go#L489-L493) and [here](https://github.com/libp2p/go-libp2p-kad-dht/blob/4371650e37662cdfd9f5777240c67b861af26092/fullrt/dht.go#L1223-L1228)) and the [peerstore](https://github.com/libp2p/go-libp2p-peerstore/blob/9f3a96b88d93dd3360236a88f1a97546261150c5/pstoremem/addr_book.go#L148-L160), where the peerstore isn't even using it in an efficient way.

Therefore, this code should probably live (unexported) inside kad.

**Comment by vgonkivs** [comment]
Hi @marten-seemann. Thanks for the explanation. Is it possible to temporary add this functionality(I can open a PR) as it's pretty logic that if there is a possibility to add a peer, then it might have possibility to delete a peer or could suggest what can I use instead of `peer.Set`(with add/remove peer functionality) if it will be deleted at all? I want to avoid copy pasting in my code

**Comment by marten-seemann** [comment]
This seems to be a trivial piece of code, so I'd argue that copy-pasting the parts that you need would actually be the right thing to do.

Also note that the API here is kind of confusing: You can set a size, but that size is not enforced by `Add` (only by `TryAdd`).

**Comment by vgonkivs** [comment]
ok, thank you.
