### ISSUE TITLE
Unable to know data on the connected node

### ISSUE THREAD

**Issue by Giancarlo1974** [libp2p/go-libp2p-core#263]
I spent all day in vain to find a small example

I wrote the classic listening echo server

Is it possible to receive an event on the server when a client connects?

I would like to know PeerID and its IP address

I tried writing this piece of code:

`
sub, err := cfg.Host.EventBus().Subscribe(&event.EvtPeerConnectednessChanged{})
	if err != nil {
		panic(err)
	}
	defer sub.Close()
`

but then I wasn't able to bind it to a function to get the data on the client

**Comment by BigLep** [comment]
Can you please ask on discuss.libp2p.io because this doesn't appear to be an issue with go-libp2p-core itself?

Thanks - closing.
