### ISSUE TITLE
use a mock clock in bandwidth counter tests

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p-core#267]
These tests are currently flaky, and we won't be able to proceed with repo consolidation (https://github.com/libp2p/go-libp2p/issues/1556) until they're fixed. Injecting a mock clock (similar to what we did in https://github.com/libp2p/go-libp2p/pull/1516/files) should be a straightforward way to test this reliably, and dramatically speed up the test at the same time.

**Comment by schomatis** [comment]
@marten-seemann I suspect I'm missing some context here and will need this laid out in a bit more detail:

> These tests are currently flaky

Which tests?

> Injecting a mock clock

Where?

**Comment by marten-seemann** [comment]
> Which tests?

The bandwidth tests.

> Where?

Into the `metrics/BandwidthCounter`. It’s using the flow metrics repo, so probably we need to do it there too. Basically, the goal is that we don’t use any calls to `time.Now()` any more, but only to a `clock.Now()`. When run in production, `clock.Now()` use `time.Now()`, but in tests we can use a mock clock.

**Comment by schomatis** [comment]
Sounds good, working on this.

**Comment by schomatis** [comment]
Upstream work in https://github.com/libp2p/go-flow-metrics/pull/18. After that lands will proceed with applying the mock clock here.
