### ISSUE TITLE
Add a method to reset BandwidthCounter

### ISSUE THREAD

**Issue by kpp** [libp2p/go-libp2p-core#64]
BandwidthCounter::Clear would be very useful to drop all previous data and start from the beginning. Restarting `ipfs daemon` is not a solution for all cases.

@Stebalien I can do that but I need help. Would you please guide me how to do this?

- [x] Add methods to clear stats https://github.com/libp2p/go-flow-metrics/pull/10
- [x] Add API to reset bandwidth counters https://github.com/libp2p/go-libp2p-core/pull/71
- [ ] ~Expose reset as part of the interface https://github.com/libp2p/go-libp2p-core/pull/72~
- [ ] https://github.com/libp2p/go-libp2p-core/pull/72#issuecomment-554602688
- [ ] Release go-libp2p-core
- [ ] Release go-libp2p
- [ ] Release go-ipfs

**Comment by Stebalien** [comment]
Fixed.
