### ISSUE TITLE
[DISCUSSION] Should the multiselect (fka Multistream 2.0) implementation live here?

### ISSUE THREAD

**Issue by bigs** [libp2p/go-libp2p-core#68]
Getting ready to start prototyping a multiselect implementation, how do we feel about it living here? It *is* core.

**Comment by bigs** [comment]
For the record, I vote yes!

**Comment by Stebalien** [comment]
I'd rather have it in a separate repo so people can use it without pulling in all of libp2p. Unlike keys, etc. It's not libp2p specific.

Also, we should probably have an actual _proposal_ to discuss before we worry about implementation.
